// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL (port 5432) for CLI operations like db push / migrate.
    // The pooled DATABASE_URL (port 6543) hangs on DDL operations.
    url: process.env["DIRECT_URL"],
  },
});
